name: Build and Publish Page

on:
  push:
    branches: [ main ]  # 触发工作流的分支，可根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dante7qx doc
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Build project
        run: |
          npm -v 
          npm install -g vuepress
          npm install dayjs 
          npm run build

      - name: Checkout dante7qx.github.io
        uses: actions/checkout@v3
        with:
          repository: dante7qx/dante7qx.github.io     # 替换为 dante7qx.github.io 的用户名和仓库名
          token: ${{ secrets.CICD_ACTION_TOKEN }} # 使用之前生成的 Personal Access Token

      - name: Commit files to dante7qx.github.io
        run: |
          cp -r docs/.vuepress/dist  ./
          git config --local user.email "sunchao.0129@163.com"
          git config --local user.name "dante7qx"
          git add .
          git commit -m "更新知识库页面"
          git push

